title: "Neall Struwig | Data Science Portfolio"
description: "Showcasing my work in data science, engineering, and research."
remote_theme: "mmistakes/minimal-mistakes"

# Author Information
author:
  name: "Neall Struwig"
  avatar: "/assets/profile.jpg" # Upload your profile picture to assets/
  bio: "Data Engineer | Research Specialist | Machine Learning Enthusiast"
  location: "Toronto, Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/neall-struwig"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/your-profile"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your-email@example.com"

# Navigation Bar
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

# Plugins (Required for Minimal Mistakes)
plugins:
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jemoji
