title: "Neall Struwig | Data Science Portfolio"
description: "Data science, analytics, and engineering projects."
author: "Neall Struwig"
theme: minimal-mistakes  # You can replace 'minima' with another theme
baseurl: "" # Keep this empty
url: "https://neall-struwig.github.io" # Your GitHub Pages URL
